base: ner
dataset: mahanama_ner_fine
backbone: google/muril-large-cased
num_classes: 77
max_length: 256
dim_model: 1024
dim_time: 256
depth: 6
time_steps: 1000
sampling_steps: 10
noise_schedule: linear
objective: pred_x0
loss_type: l2
self_condition: True
snr_scale: 0.1
ddim_sampling_eta: 1.0
add_lstm: False
freeze_bert: False
compound_aware: False
use_graph_encoder: False
use_contrastive: False
use_mst: False

max_epochs: 20
batch_size: 16
lr_bert: 1e-5
lr_other: 1e-5
weight_decay: 1e-5
warmup_steps: 1000
warmup_ratio: 0
lr_scheduler_type: linear
optimizer_type: AdamW
num_workers: 2
use_gpu: True
gpus: 0
output_dir: output
logger: None
test_path: False
model_path: model.pt
save_limit: 3
